Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/bionic64'

  config.vm.provider :virtualbox do |virtualbox, override|
    virtualbox.memory = 1024
  end

  config.vm.define 'prometheus' do |prom|
    prom.vm.host_name = 'prom'
    prom.vm.network :private_network, ip: '10.0.0.10'
  end

  config.vm.define 'nginx' do |nginx|
    nginx.vm.host_name = 'nginx'
    nginx.vm.network :private_network, ip: '10.0.0.11'
  end

  config.vm.define 'grafana' do |grafana|
    grafana.vm.host_name = 'grafana'
    grafana.vm.network :private_network, ip: '10.0.0.12'
  end
end
